// Procedural, dependency-free Web Audio API sound library.
const pick=a=>a[Math.floor(Math.random()*a.length)], r=(a,b)=>a+Math.random()*(b-a);
export class SoundEffects{constructor({volume=.18}={}){this.volume=volume;this.context=null} #ctx(){if(!this.context)this.context=new AudioContext();if(this.context.state==='suspended')this.context.resume();return this.context} #tone(f,d=.1,type='sine',to,vol=this.volume){const c=this.#ctx(),n=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(f,n);if(to)o.frequency.exponentialRampToValueAtTime(Math.max(20,to),n+d);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(vol,n+.006);g.gain.exponentialRampToValueAtTime(.0001,n+d);o.connect(g).connect(c.destination);o.start(n);o.stop(n+d+.02)}
  activate(){this.#tone(1180,.045,'square',820,this.volume*.62)} tap(){this.activate()} alert(){[620,900].forEach((f,i)=>setTimeout(()=>this.#tone(f,.11,'sine',null,this.volume*.55),i*95))} popover(){this.alert()} rotor(){this.#tone(520,.04,'square',330,this.volume*.5)} scrollClick(){this.rotor()} talkbackFocus(){this.#tone(260,.035,'triangle',null,this.volume*.42)} talkbackMove(){this.talkbackFocus()} nvdaBoundary(){this.#tone(150,.16,'triangle',95,this.volume*.55)} nvdaError(){this.#tone(115,.22,'sawtooth',70,this.volume*.6)} jawsMessage(){this.#tone(1040,.055,'square',760,this.volume*.5)} jawsChirp(){this.jawsMessage()}
  clickin(){[440,660,880].forEach((f,i)=>setTimeout(()=>this.#tone(f,.075,'square',null,this.volume*.72),i*58))} clickout(){[440,300,190].forEach((f,i)=>setTimeout(()=>this.#tone(f,i===2?.16:.085,'triangle',null,this.volume*.62),i*62))} switchOn(){this.#tone(520,.06,'square',780,this.volume*.58)} switchOff(){this.#tone(520,.06,'square',260,this.volume*.5)} success(){[523,659,784].forEach((f,i)=>setTimeout(()=>this.#tone(f,.1,'sine',null,this.volume*.6),i*65))} warning(){this.#tone(760,.12,'triangle',520,this.volume*.55)} delete(){this.#tone(620,.22,'sawtooth',100,this.volume*.4)} trash(){this.delete()} sheetOpen(){this.#tone(220,.18,'sine',520,this.volume*.45)} modalDismiss(){this.#tone(520,.12,'sine',220,this.volume*.4)}
  blueClick(){this.#tone(2600,.045,'square',1800,this.volume*.65)} brownBump(){this.#tone(1500,.06,'triangle',900,this.volume*.5)} redThud(){this.#tone(110,.09,'sine',70,this.volume*.48)} laser(){this.#tone(1500,.22,'sawtooth',90,this.volume*.6)} coin(){[880,1320].forEach((f,i)=>setTimeout(()=>this.#tone(f,.09,'square',null,this.volume*.55),i*65))} jump(){this.#tone(280,.2,'square',1100,this.volume*.55)} warp(){this.#tone(180,.5,'sawtooth',1800,this.volume*.45)} teleport(){[500,700,1000,1400].forEach((f,i)=>setTimeout(()=>this.#tone(f,.1,'sine',null,this.volume*.38),i*45))} explosion(){const c=this.#ctx(),n=c.currentTime,b=c.createBuffer(1,c.sampleRate*.35,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=c.createBufferSource(),g=c.createGain();g.gain.setValueAtTime(this.volume*.7,n);g.gain.exponentialRampToValueAtTime(.0001,n+.35);s.buffer=b;s.connect(g).connect(c.destination);s.start()}
  chaos({voices=Math.floor(r(2,7))}={}){for(let i=0;i<voices;i++)this.#tone(r(70,1600),r(.05,.5),pick(['square','sawtooth','triangle','sine']),r(40,1800),this.volume*.35)} randomSound(o){this.chaos(o)}
}
export const soundEffects=new SoundEffects();
