// Lightweight Web Audio API sound effects module.
const pick=(items)=>items[Math.floor(Math.random()*items.length)]; const between=(min,max)=>min+Math.random()*(max-min);
export class SoundEffects { constructor({volume=.18}={}){this.volume=volume;this.context=null;} #ensureContext(){if(!this.context)this.context=new AudioContext();if(this.context.state==='suspended')this.context.resume();return this.context;} #tone({frequency,duration=.08,type='sine',slideTo,volume=this.volume}){const c=this.#ensureContext(),n=c.currentTime,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.setValueAtTime(frequency,n);if(slideTo)o.frequency.exponentialRampToValueAtTime(Math.max(20,slideTo),n+duration);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(volume,n+.006);g.gain.exponentialRampToValueAtTime(.0001,n+duration);o.connect(g).connect(c.destination);o.start(n);o.stop(n+duration+.01);} click(){this.#tone({frequency:900,duration:.045,type:'square',slideTo:520});} success(){this.#tone({frequency:523.25,duration:.09});setTimeout(()=>this.#tone({frequency:783.99,duration:.14}),70);} error(){this.#tone({frequency:180,duration:.18,type:'sawtooth',slideTo:110});} clickin(){[440,660,880].forEach((frequency,i)=>setTimeout(()=>this.#tone({frequency,duration:.075,type:'square',volume:this.volume*.72}),i*58));} clickout(){[440,300,190].forEach((frequency,i)=>setTimeout(()=>this.#tone({frequency,duration:i===2?.16:.085,type:'triangle',volume:this.volume*.62}),i*62));}
  activate(){this.#tone({frequency:1180,duration:.045,type:'square',slideTo:820,volume:this.volume*.62});}
  alert(){[620,900].forEach((frequency,i)=>setTimeout(()=>this.#tone({frequency,duration:.11,type:'sine',volume:this.volume*.55}),i*95));}
  talkbackFocus(){this.#tone({frequency:260,duration:.035,type:'triangle',volume:this.volume*.42});}
  talkbackMove(){this.talkbackFocus();}
  nvdaBoundary(){this.#tone({frequency:150,duration:.16,type:'triangle',slideTo:95,volume:this.volume*.55});}
  jawsMessage(){this.#tone({frequency:1040,duration:.055,type:'square',slideTo:760,volume:this.volume*.5});}
  chaos({voices=Math.floor(between(2,6))}={}){const c=this.#ensureContext(),n=c.currentTime,d=between(.12,.65),m=c.createGain();m.gain.setValueAtTime(.0001,n);m.gain.exponentialRampToValueAtTime(this.volume*.7,n+.01);m.gain.exponentialRampToValueAtTime(.0001,n+d);m.connect(c.destination);for(let i=0;i<voices;i++){const o=c.createOscillator(),g=c.createGain(),s=n+between(0,.04),l=between(.06,d);o.type=pick(['square','sawtooth','triangle','sine']);o.frequency.setValueAtTime(between(90,1400),s);o.frequency.exponentialRampToValueAtTime(between(45,1800),s+l);g.gain.setValueAtTime(.0001,s);g.gain.exponentialRampToValueAtTime(between(.15,.8),s+.005);g.gain.exponentialRampToValueAtTime(.0001,s+l);o.connect(g).connect(m);o.start(s);o.stop(s+l+.01);}} randomSound(options){this.chaos(options);}}
export const soundEffects=new SoundEffects();
